### ISSUE TITLE
Export JS Modules instead of CommonJS

### ISSUE THREAD

**Issue by TremayneChrist** [pelotoncycle/resize-observer#17]
Would be good to update the exported `./lib` files to use JS Modules. Otherwise it's easy to bump into this error:

```
Uncaught SyntaxError: The requested module '../node_modules/resize-observer/lib/ResizeObserver.js' does not provide an export named 'ResizeObserver'
```

**Comment by niiyeboah** [comment]
@TremayneChrist what was the solution to this issue?

**Comment by TremayneChrist** [comment]
Hi @niiyeboah I never got any responses from a couple of issues I posted here and I had some other issues with measurement and notifications. The solution was that I built another resize observer polyfill...

**Comment by niiyeboah** [comment]
Ok thanks! That's good to know
