### ISSUE TITLE
usage with debounce

### ISSUE THREAD

**Issue by kodeine** [pelotoncycle/resize-observer#23]
is it possible to use debounce for the observer?

**Comment by devrelm** [comment]
The `ResizeObserver` callback already runs at most once per animation frame (once per draw to the screen; approx. 60 times per second), so there shouldn't be any need to throttle or debounce in most cases.

That said, if you would like to debounce using something like [`lodash.debounce`](https://lodash.com/docs#debounce), you should be able to do that by wrapping your callback before passing it to the `ResizeObserver` constructor:

```js
import * as debounce from 'lodash.debounce';
import { ResizeObserver } from 'resize-observer';

const callback = debounce(
  () => console.log("I'll only run 250ms after the body has finished resizing"),
  250,
);
const ro = new ResizeObserver(callback);
ro.observe(document.body);
```
